config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #On veut que la racine du site se soit artworks-index
  root to: 'artworks#index'
  resources :artworks do
  	resources :rentals, only: [:new, :create, :delete] # show ?
    collection do
      get :my_artworks
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rentals, only: [:index] do
    member do
    patch "accept_rentals", to: "rentals#accept_rentals"
    patch "decline_rentals", to: "rentals#decline_rentals"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  # before_create :set_default_picture
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_one_attached :photo
  has_many :rentals

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :dimension, presence: true
  CATEGORY = ["Painting", "Sculpture", "Installation", "Photography", "Video"]
  validates :category, inclusion: { in: CATEGORY}
  # def set_default_picture
  #   self.photo = 'app/assets/images/filler_picture.jpg'
  # end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :artwork

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :artworks, dependent: :destroy
  has_many :rentals, dependent: :destroy
  # has_many :owner_rentals, through: :artworks, source: :rental
  has_one_attached :photo
  def owner_rentals
    self.artworks.map(&:rentals).flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

  def index

    if params[:query].present?
      @artworks = Artwork.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @artworks = Artwork.all
    end

    @artworks_geo = Artwork.geocoded
    @markers = @artworks_geo.map do |artwork|
      {
        lat: artwork.latitude,
        lng: artwork.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { artwork: artwork })
      }
    end

  end

  def show
    @artwork = Artwork.find(params[:id])
    @rental = Rental.new
    if @artwork.geocode
      @marker =
        {
          lat: @artwork.latitude,
          lng: @artwork.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { artwork: @artwork })
        }
    end
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user
    @artwork.save!
    redirect_to my_artworks_artworks_path
  end

  def edit
    @artwork = Artwork.find(params[:id])
  end

  def update
    @artwork = Artwork.find(params[:id])
    @artwork.update(artwork_params)
    redirect_to artwork_path(@artwork)
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    redirect_to my_artworks_artworks_path
  end

  def my_artworks
    @artworks = Artwork.where(user: current_user)
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :description, :price, :category, :dimension, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @user = current_user
    @rentals = Rental.all
  end
  def new
    @artwork = Artwork.find(params[:artwork_id])
    @rental = Rental.new
  end

  def accept_rentals
    @rental = Rental.find(params[:id])
    @rental.status = "Accepted"
    @rental.save
    redirect_to rentals_path
  end

  def decline_rentals
    @rental = Rental.find(params[:id])
    @rental.status = "Declined"
    @rental.save
    redirect_to rentals_path
  end

  def create
    @user = current_user
    @rental = Rental.new(rental_params)
    @artwork = Artwork.find(params[:artwork_id])
    @rental.artwork = @artwork
    @rental.user = @user
    @rental.status = "Pending"
    if @rental.save
      redirect_to artwork_path(@artwork)
    else
      render 'new'
    end
  end

  def delete
    @rental = Rental.find(params[:rental_id])
    @rental.destroy
    redirect_to artworks_path
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_info_window.html.erb
<p><%= artwork.address %></p>
<h2><%= artwork.title %></h2>

app/views/artworks/edit.html.erb
<div class="d-flex container justify-content-center">
  <h3>Update my artwork info</h3>
</div>

<div class="container justify-content-center">
  <%= simple_form_for [ @artwork ] do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :dimension %>
    <%= f.input :category %>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Cancel', artwork_path, class: "btn btn-danger m-4" %>
</div>

app/views/artworks/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(<%= asset_path 'banner2.jpg'%>)">
	<h1>Art'BNB</h1>
	<h3>Rent your art</h3>
</div>

	<div class="info-container d-flex bd-highlight">
		<div class="p-2 flex-grow-1 bd-highlight">
			<%= form_tag artworks_path, method: :get do %>
			<%= text_field_tag :query,
				params[:query],
				class: "form-control",
				placeholder: "Find an artwork"
			%>
		</div>
		<div class="p-2 bd-highlight">
		<%= submit_tag "Search", class: "btn btn-primary" %>
		<% end %>
		</div>
	</div>

<div class="container">
	<div class="col-12 d-flex">
		<div class="col-8">
			<div class="artworks row">
				<% @artworks.each do |artwork| %>
					<div class="col-4">
						<%= link_to artwork_path(artwork), class: "" do %>
							<div class="card_artwork">
								<% if artwork.photo.attached? %>
									<%= cl_image_tag artwork.photo.key, crop: :fill%>
								<% else %>
					    		 <%= image_tag "filler_picture.jpg", alt: "alttext" %>
					  		<% end %>
					  		<div class="text-center">
								<p id="title"><%= artwork.title %></p>
								<p id="price"><%= artwork.price %> €/day</p>
								</div>
							</div>
						<% end %>
						</div>
					<% end %>
			</div>		
		</div>
		<div class="col-4 p-0">
			<div id="map"
			     style="width: 100%; height: 600px;"
			     data-markers="<%= @markers.to_json %>"
			     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
			</div>
		</div>	
	</div>
</div>

app/views/artworks/my_artworks.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'banner.jpg'%>)">
  <h1>Art'BNB</h1>
  <h3>Rent your art</h3>
</div>

<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <h3>Here are the artworks you own</h3>
      <h5><em>Click on any item to access details</em></h5>
    </div>
    <div>
      <%= link_to '✚ Add new artwork', new_artwork_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="artworks row">
    <% @artworks.each do |artwork| %>
      <div class="col-3">
        <%= link_to artwork_path(artwork), class: "" do %>
          <div class="card_artwork">
            <% if artwork.photo.attached? %>
              <%= cl_image_tag artwork.photo.key, crop: :fill%>
            <% else %>
               <%= image_tag "filler_picture.jpg", alt: "alttext" %>
            <% end %>
            <div class="text-center">
              <p id="title"><%= artwork.title %></p>
              <p id="price"><%= artwork.price %> €/day</p>
            </div>
          </div>
        <% end %>
        </div>
      <% end %>
</div>

app/views/artworks/new.html.erb
<div class="container">
	<h1>Add an artwork</h1>
	<div class="banner" id="banner2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'banner2.jpg'%>)"></div>

  <%= simple_form_for [ @artwork ] do |f| %>
    <%= f.input :title, placeholder: 'Short title of your artwork', input_html: { style: "input-group-sm mb-3"}  %>
    <%= f.input :address, placeholder: 'Where is your artwork' %>
    <%= f.input :photo, as: :file %>
    <%= f.input :description, placeholder: 'Description of your artwork here. Be accurate and make people want to rent your artwork 🙂' %>
    <%= f.input :dimension, placeholder: 'Those are things that will matter' %>
    <%= f.input :price, placeholder: 'How much will it cost to rent your artwork for a day (euros)?'%>
<!--     On va chercher la constante dans le model -->
    <%= f.input :category, collection: Artwork::CATEGORY, prompt: "What kind of artwork is it?", crop: :fill%>
    <%= f.submit "Add the artwork", class: "btn btn-primary" %>
  <% end %>
<%#= link_to 'Back', artworks_path %>
</div>

app/views/artworks/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
  	<div id="title">
  	  <%= @artwork.title %> (<%= @artwork.category %>)
  	</div>
    <div>
      <% if @artwork.user == current_user %>
         <%= link_to '✏️ Edit this artwork', edit_artwork_path, class: "align-middle edit-button"%>
      <% end %>
    </div>
    <div>
    <% if @artwork.user == current_user %>
         <%= link_to "❌ Delete this artwork",
          artwork_path(@artwork), class:"text-danger delete-button",
          method: :delete,
          data: { confirm: "Delete this artwork? This can't be undone!" } %>

      <% end %>
    </div>
  </div>

  <div class="d-flex row">
  	<div id="picture" class="col-8">
  	  <% if @artwork.photo.attached? %>
                <%= cl_image_tag @artwork.photo.key, crop: :fill, style: "width: 100%", class:"align-middle"%>
              <% else %>
              <%= image_tag "filler_picture.jpg", alt: "alttext", crop: :fill, style: "height:400px; width: auto", class:"align-middle"%>
      <% end %>
  	</div>
    <div id="map" class="col-4">
         style="width: 100%; height: 400px;"
         data-marker="<%= @marker.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"Map here
    </div>
  </div>

	<div class="info-container">
			<div id="description">
			  ℹ️ <%= @artwork.description %>
			</div>

			<div id="dimension">
			  📐 "<%= @artwork.dimension %>
			</div>

			<div class="text-right">
			  <span id="artwork-price"><%= @artwork.price %></span> €/day
			</div>
	</div>

  <% if @artwork.user != current_user %>
  	<div class="form-wrapper">
  	<h2>Would you like to book this artwork? </h2>
    <h6><em>Select your dates to send a request to the owner :)</em></h6>
  		<%= simple_form_for [@artwork, @rental] do |f| %>
  		<%= f.input  :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  		<%= f.input  :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  		<%= f.button :submit, "Book", class: "btn btn-primary" %>
  		<% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% user_signed_in? %>
    <% current_user %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600&family=Playfair+Display:wght@400;500;700&display=swap" rel="stylesheet">
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
        <%= render 'shared/tabs' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
<!--     <div class="container"> -->
        <div class="content-wrapper">
          <%= yield %>
        </div>
<!--     </div> -->
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<div>
  <div> @my_rentals </div>
  <div></div>
</div>

app/views/pages/_footer.html.erb
<footer>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This website is made with <i class="fas fa-heart"></i> by the UX-comparator team
    </div>
  </div>
</footer>

app/views/pages/home.html.erb
<%= render 'tabs' %>

app/views/rentals/index.html.erb
<div class="main_container">
  <h4 class="title"> Hello <%= @user.name %>, these are the artworks you booked!</h4>

  <% @user.rentals.each do |rental| %>
    <div class="card-trip">
      <% if  rental.artwork.photo.attached? %>
        <%= cl_image_tag rental.artwork.photo.key, alt: "alttext" %>
      <% else %>
        <%= image_tag "filler_picture.jpg", alt: "alttext" %>
      <% end %>
  <div class="card-trip-infos">
    <div class="text_design">
      <h2 class="title2"><%= rental.artwork.title %></h2>
     <p class="description"><%= rental.artwork.description %></p>
    </div>
    <h2 class="card-trip-pricing"><%= rental.artwork.price %> $ </h2>
  </div>
  <div class="div_btn">
        <%= link_to "modify", "rentals#edit", class: "btn_green" %>
        <%= link_to "cancel", "rentals#destroy", class: "btn_red" %>
  </div>
   <% if  rental.status == "Accepted" %>
    <% end %>
    <% if rental.status == "Declined" %>
    <% end %>
    <% if  rental.status == "Pending" %>
   <% end %>
  </div>

 <% end %>

<h4 class="title"> These are the artworks you offered to rent!</h4>
<div>
    <% @user.owner_rentals.each do |rental| %>
  <div class="card-trip">
    <% if  rental.artwork.photo.attached? %>
    <%= cl_image_tag rental.artwork.photo.key, alt: "alttext" %>
    <% else %>
    <%= image_tag "filler_picture.jpg", alt: "alttext" %>
    <% end %>
  <div class="card-trip-infos">
    <div class="text_design">
      <h2 class="title2"><%= rental.artwork.title %></h2>
      <div class= "info_resa">
        <h2 class="status">Status: <%=rental.status %></h2>
        <h2 class="date"><%= rental.start_date %> / <%= rental.end_date %></h2>
      </div>
      <p class="description"><%= rental.artwork.description %></p>
    </div>
  </div>
  <div class="div_btn">
      <%= link_to "Accept", accept_rentals_rental_path(rental), class:"btn_green", method: :patch, remote: true%>
      <%= link_to "Decline", decline_rentals_rental_path(rental), class:"btn_red", method: :patch, remote: true %>
  </div>
</div>
<% end %>
</div>

app/views/rentals/new.html.erb
<h1>Booking</h1>

app/views/rentals/show.html.erb
<h1> Hello <%= @user.name %>, these are your rentals! </h1>
<div>
<ul>
  <%= @user.rentals.each do |rental| %>
  <li><%= rental.artwork.title %></li>
  <%= link_to "Need some idea?", "artworks#index", class: "btn-primary" %>
  <%= link_to "Need some idea?", "artworks#index", class: "btn-primary" %>
  <% end %>
</ul>
<%= link_to "Need some idea?", "artworks#index", class: "btn-primary" %>
</div>






<!-- t.string "start_date"
    t.string "end_date"
    t.string "status"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "user_id", null: false
    t.index ["user_id"], name: "index_rentals_on_user_id" -->

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This website is made with <i class="fas fa-heart"></i> by the UX-comparator team
    </div>
  </div>
</footer>

app/views/shared/_index_owner_rentals.html.erb
<h1> Hello <%= @user.name %>, these are your artworks reservations! </h1>
<div>
<ul>
  <%= @rental.user.name.each do |rental| %>
  <li><%= rental.artwork.title %> / <%= rental.user.name %></li>
  <% end %>
</ul>
<%= link_to "Need some idea?", "artworks#index", class: "btn-primary" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Home', artworks_path(@artwork), class: "navbar" %>
        </li>
        <ul class="list-inline tabs-underlined">
          <li>
            <a href="#" class="tab-underlined active"><%= link_to 'All artworks', artworks_path(@artwork) %></a>
          </li>
          <li>
            <a href="#" class="tab-underlined"><%= link_to 'My artworks', my_artworks_artworks_path %></a>
          </li>
          <li>
            <a href="#" class="tab-underlined"><%= link_to 'My rentals', rentals_path %></a>
          </li>
        </ul>

        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon compte", "#", class: "dropdown-item" %>
            <%= link_to "Paramètres", "#", class: "dropdown-item" %>
            <%= link_to "FAQ", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>